### ISSUE TITLE
Have a single way to interact with OpenShift API

### ISSUE THREAD

**Issue by aditya-konarde** [app-sre/qontract-reconcile#112]
Currently, the `openshift-resources` subcommand talks to openshift API with a wrapper to the binary, while the `openshift-rolebindings` integration uses `requests` to talk directly to the OpenShift api. 

This is causing confusion debugging, where we are seeing one of the integration fail on an SSL cert verification check, while the others interacting with OpenShift work just fine.

Proposal: We should have a uniform way of talking to the OpenShift API across integrations.

CC @jmelis @maorfr

**Comment by jmelis** [comment]
Totally! @maorfr is planning on rewriting openshift-rolebindings to use `oc` instead of the API. :100: !

**Comment by maorfr** [comment]
created https://jira.coreos.com/browse/APPSRE-897
